version: '3.8'

services:
  # Servidor PHP
  php-fpm:
    build:
      args:
        user: ${SO_USER}
        uid: 1000
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php8.0.ini:/usr/local/etc/php/php.ini
    networks:
      - laravelnet

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - laravelnet

  ### PostgreSQL Server Container ##################################
#  db_postgres:
#    build:
#      context: ./docker/postgres
#    volumes:
#      - db-postgres:/var/lib/postgresql/data
#    ports:
#      - "${POSTGRES_EXTERNAL_PORT}:5432"
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    networks:
#      - laravelnet

  # Mysql
  db_mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge

volumes:
  db-postgres:
    driver: local
